[tool.poetry]
name = "bloodhoundcli"
version = "0.0.9"
description = ""
authors = ["dadevel <dadevel@disroot.org>"]
license = "MIT"
readme = "README.md"
packages = [{include = "bloodhoundcli"}]

[tool.poetry.scripts]
bloodhoundcli = "bloodhoundcli.main:main"

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.7"
requests = "^2.31.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
